dist: trusty

language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
    - WP_VERSION=trunk WP_MULTISITE=0
    - WP_VERSION=trunk WP_MULTISITE=1

before_script:
    - npm install
    - export DEV_LIB_PATH=node_modules/wp-dev-lib
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh
